# Generated by Django 4.2.5 on 2023-09-22 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0006_rename_spares_order_spare_alter_order_date_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='spare',
            new_name='spares',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_complete',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 17, 19, 32, 102399, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 17, 19, 32, 102399, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_formation',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 17, 19, 32, 102399, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Injected', 'Введён'), ('At work', 'В работе'), ('Сompleted', 'Завершён'), ('Cancelled', 'Отменён'), ('Deleted', 'Удалён')], default='Injected', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='description',
            field=models.TextField(default='Описание авиазапчасти', max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='name',
            field=models.CharField(default='Название авиазапчасти', max_length=100, verbose_name='Название'),
        ),
    ]
