# Generated by Django 4.2.5 on 2023-09-22 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0007_rename_spare_order_spares_alter_order_date_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_complete',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 17, 19, 44, 566350, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 17, 19, 44, 566350, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_formation',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 17, 19, 44, 566350, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования'),
        ),
    ]
